---
title: "OHDSI HSIG"
description: "Health Systems Interest Group"
format: html
engine: knitr

about:
  id: about
  template: jolla
  links:
    - text: '{{< iconify material-symbols:info>}} About'
      href: about.qmd
    - text: "{{< iconify material-symbols:forum>}} Forums"
      href: https://forums.ohdsi.org/
    - text: '{{< iconify mdi:blog>}} Wiki'
      href: https://www.ohdsi.org
    - text: '{{< iconify mdi:github>}} GitHub'
      href: https://github.com/OHDSI/HealthSystems
    - text: '{{< iconify material-symbols:co-present>}} Global Symposium'
      href: https://www.ohdsi.org/ohdsi2024/

---

::: {#about}
:::

{{< pagebreak >}}

::: {.column-page}

# Welcome to OHDSI Health Systems Interest Group

The Observational Health Data Sciences and Informatics (or OHDSI, pronounced "Odyssey") program is a multi-stakeholder, interdisciplinary collaborative to bring out the value of health data through large-scale analytics. All our solutions are open-source.

OHDSI’s mission - To improve health by empowering a community to collaboratively generate the evidence that promotes better health decisions and better care.

**Healthcare Systems Interest Group mission** - To help each other and learn from experience.
Our group mainly supports health systems, hospitals, and others who have electronic health record (EHR) data on their OHDSI journey to produce reliable, reproducible evidence.

The Health Systems group meets every other Monday at 10am Eastern Time. Please join us on the [MS Teams call](https://teams.microsoft.com/l/team/19%3A2b9db953a46441c8be51cb3d3785cac3%40thread.tacv2/conversations?groupId=198ebad0-c5b9-4991-8a5e-55e6d71cb817&tenantId=a30f0094-9120-4aab-ba4c-e5509023b2d5)



# Collaborators say...
:::

::: {.index-grid}

::: {.index-g-col-4 .card .border-light .mb-3 .text-center}
::: {.card-body}
["This block would include a quote from an academic source."]{.card-text}

[Academic Quote Source]{.blockquote-footer}
:::
:::

::: {.index-g-col-4 .card .border-light .mb-3 .text-center}
::: {.card-body}
["This block would include a quote from a government source."]{.card-text}

[Government Quote Source]{.blockquote-footer}
:::
:::

::: {.index-g-col-4 .card .border-light .mb-3 .text-center}
::: {.card-body}
["This block would include a quote from an industry source."]{.card-text}

[Industry Quote Source]{.blockquote-footer}
:::
:::
